instance_destroy()
instance_create_layer(x, y - 5, "Instances", obj_disparo_boss_4)
instance_create_layer(x, y - 5, "Instances", obj_disparo_boss_4)
instance_create_layer(x, y - 5, "Instances", obj_disparo_boss_4)
instance_create_layer(x, y - 5, "Instances", obj_disparo_boss_4)
instance_create_layer(x, y, "Instances", obj_effects_explosion_boss)